.github/workflows/ci.yml, appspec.yml, build.gradle, scripts/deploy.sh, scripts/start.sh, scripts/switch.sh, src/main/java/com/hyperlink/server/global/profile/controller/ProfileController.java
- Dev 환경에 머지할 때 적용될 CI를 생성했습니다.
- Dev 환경에 머지할 때 적용될 CI를 생성했습니다.
- CI / CD 특성상 머지 먼저 하는 점 양해부탁드립니다.
- Develop/v0.1 브랜치를 CI/CD 적용을 위해 미리 생성했습니다.
- 아직 #5 이슈를 마무리하지 않았기 때문에 이슈를 닫지 않겠습니다.
close #5
=> [#5] Dev 환경 CI 생성

src/main/resources/db/migration/V3__auto_increment.sql
- DB 전체 테이블 PK auto increment 설정 추가
- DB insert 작업 시에 PK 값이 auto increment 되도록 설정했어요
close #26
=> [#26] DB 전체 테이블 PK auto increment 설정 추가

.github/workflows/ci-prod.yml, .github/workflows/ci.yml, build.gradle, lombok.config, scripts/deploy.sh, scripts/start.sh, scripts/switch.sh, src/main/java/com/hyperlink/server/domain/member/MemberService.java, src/main/java/com/hyperlink/server/domain/memberContent/domain/entity/MemberContent.java, src/main/java/com/hyperlink/server/domain/memberContent/domain/entity/MemberContentActionType.java, src/main/resources/db/migration/V3__auto_increment.sql
- api base uri 변경
- RDS 세팅 변경
- develop/v0.1 버전의 설정을 main 브랜치로 전파
- 이번 머지는 예외적으로  api base uri를 변경하기 위한 main 머지입니다.
- 앞으로 main 브랜치로의 머지는 스프린트 마지막 날 진행합니다.
close #30
=> [#30] main 브랜치에 대해 api base uri 변경

.github/workflows/ci-prod.yml
- 기존 prod 배포용 s3 버킷을 삭제하고 dev 배포용 s3 버킷으로 통합
- prod 배포용 s3 버킷 삭제
- 새로운 s3 이미지 버킷 생성
- 환경 구성이니만큼 리뷰어 등록 후 리뷰 없이 머지하겠습니다.
close #42
=> [#42] prod 배포 s3 bucket 삭제

src/docs/asciidoc/api.adoc, src/main/java/com/hyperlink/server/domain/content/domain/entity/Content.java, src/main/java/com/hyperlink/server/domain/member/domain/entity/Member.java, src/main/java/com/hyperlink/server/domain/memberContent/application/MemberContentService.java, src/main/java/com/hyperlink/server/domain/memberContent/controller/MemberContentController.java, src/main/java/com/hyperlink/server/domain/memberContent/domain/MemberContentRepository.java, src/main/java/com/hyperlink/server/domain/memberContent/exception/BookmarkExistedException.java, src/main/java/com/hyperlink/server/domain/memberContent/exception/BookmarkNotFoundException.java, src/main/resources/db/migration/V3__auto_increment.sql, src/test/java/com/hyperlink/server/memberContent/application/MemberContentServiceIntegrationTest.java, src/test/java/com/hyperlink/server/memberContent/controller/MemberContentControllerTest.java, src/test/java/com/hyperlink/server/memberContent/repository/MemberContentRespositoryTest.java
- 북마크 추가/삭제 API 구현
- 개별 콘텐츠에 대한 특정 유저의 북마크 여부 확인 기능 구현 (isBookmarked 메소드)
- 북마크 추가/삭제 API를 구현했어요
- 개별 콘텐츠에 대한 특정 유저의 북마크 여부 확인 기능을 구현했어요 (isBookmarked 메소드)
- API에서 북마크 여부 응답값이 필요하신 분들은 해당 메소드를 사용하시면 돼요!
close #21
=> [#21] 북마크 추가/삭제 API 구현

src/main/java/com/hyperlink/server/domain/content/application/ContentService.java, src/main/java/com/hyperlink/server/domain/content/domain/entity/Content.java, src/main/java/com/hyperlink/server/domain/content/exception/ContentNotFoundException.java, src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java
- 특정 컨텐츠 조회수 개수 조회 기능 구현 (service class 메소드)
- 특정 컨텐츠 조회수 개수 조회 기능 구현
- API 응답값으로 조회수 개수가 필요하신 분들은 해당 메소드를 사용하시면 돼요!
close #39
=> [#39] 조회수 개수 조회 기능 구현

src/main/java/com/hyperlink/server/domain/content/domain/entity/Content.java, src/main/resources/db/migration/V6__add_column_category_id.sql
- Content 테이블 creator_id 컬럼 추가
- 새로운 컬럼 추가에 따른 Content 테이블 변경
- Content 테이블 creator_id 컬럼 추가
- 새로운 컬럼 추가에 따른 Content 테이블 변경
- 작업하면서 처음에 Category id 추가로 잘못 입력되어 있던 부분이 있었고 이를 다시 Creator id 추가로 수정했습니다.
close #49
=> [#49] Content 테이블 크리에이터 id 컬럼 추가

src/main/java/com/hyperlink/server/domain/content/application/ContentService.java, src/main/java/com/hyperlink/server/domain/content/domain/ContentRepository.java, src/main/java/com/hyperlink/server/domain/content/domain/entity/Content.java, src/main/resources/db/migration/V7__alter_column_content.sql, src/main/resources/db/migration/V8__change_column_name.sql, src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java, src/test/java/com/hyperlink/server/content/domain/ContentRepositoryTest.java
- content table 컬럼 정보 수정
- 좋아요 개수 컬럼 추가
- 조회수 컬럼명 변경
- 연관 작업 때문에 머지 먼저할게요!!
close #51
=> [#51] content table 컬럼 정보 수정

src/main/java/com/hyperlink/server/domain/memberCreator/domain/entity/MemberCreator.java, src/main/resources/db/migration/V9__add_table_member_creator.sql
- memberCreator table 생성
- 멤버의 특정 크리에이터 비추천 관리를 위한 table 생성
close #61
=> [#61] memberCreator table 생성

src/main/resources/db/migration/V11__add_FK_column.sql
- Content, Creator 테이블 FK 설정
- Content, Creator 테이블 FK 설정
- 이전 PR(#63)에서 누락했던 FK 설정을 완료했습니다.
close #60
=> [#60] Content의 카테고리 단일화

src/main/java/com/hyperlink/server/domain/category/domain/entity/Category.java, src/main/java/com/hyperlink/server/domain/creator/domain/entity/Creator.java, src/main/resources/db/migration/V12__alter_column_creator_category_name.sql
- Creator, Category의 name 컬럼을 unique로 변경
- Flyway 사용하여 Creator, Category의 name 컬럼을 unique로 변경함
close #69
=> [#69] Creator, Category 이름 unique로 변경하기

src/main/java/com/hyperlink/server/domain/content/domain/entity/Content.java, src/main/resources/db/migration/V13__add_column_is_viewable.sql, src/main/resources/db/migration/V14__alter_column_is_viewable.sql
- 크롤링한 Content 데이터들은 최초에 DB에 들어갈 때 사용자에게 보이지 않는 상태로 저장되게 됩니다.
- 이를 위해, isViewable 컬럼이 추가되어야 한다고 회의했었고 이 번에 해당 컬럼을 추가했습니다!
- Content 테이블에 isViewable Boolean 컬럼을 추가했습니다.
- application.yml 파일이 변경되었습니다. 적용 부탁드립니다. 이번 application.yml은 적용하지 않을 시 Spring Application이 로드되지 않습니다!
close #72
=> [#72] Content 테이블 isViewable 컬럼 추가

.github/workflows/ci.yml, src/main/java/com/hyperlink/server/domain/content/domain/entity/Content.java, src/main/java/com/hyperlink/server/domain/creator/domain/entity/Creator.java, src/main/java/com/hyperlink/server/domain/member/domain/entity/Member.java, src/main/java/com/hyperlink/server/global/exception/GlobalExceptionHandler.java, src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java, src/test/java/com/hyperlink/server/content/controller/ContentControllerTest.java, src/test/java/com/hyperlink/server/content/domain/ContentRepositoryTest.java, src/test/java/com/hyperlink/server/memberContent/application/MemberContentServiceIntegrationTest.java, src/test/java/com/hyperlink/server/memberContent/controller/MemberContentControllerTest.java
- 테스트 오류 해결
- exceptionHandler 응답 방식 통일
- 조회수 동시성 테스트 insert, update 분리
- 하나의 트랜잭션에서 동시에 insert, update문이 나가면서 데드락 발생
- 트랜잭션을 분리하여 해결함
- CI 파일에서 test, adocs 실행하게 변경
close #65
=> [#65] 테스트 오류 해결

src/main/java/com/hyperlink/server/domain/member/domain/entity/Member.java, src/main/resources/db/migration/V15__add_column_gender_and_isadmin.sql, src/main/resources/db/migration/V16__change_column_name.sql
- Member 테이블에 gender, isAdmin 컬럼 추가
- Member 테이블에 gender, isAdmin 컬럼 추가
close #52
=> [#52] Member 테이블에 gender, isAdmin 컬럼 추가

src/main/java/com/hyperlink/server/domain/content/application/ContentService.java, src/main/java/com/hyperlink/server/domain/content/dto/ContentResponse.java, src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java, src/test/java/com/hyperlink/server/content/controller/ContentControllerTest.java
- ContentResponse DTO creatorName 응답값 추가
- DTO 응답값 추가 후 연동되는 테스트 코드 변경 작업
영빈님도 보면 좋을 것 같아서 리뷰어 등록했어요 👀
close #81
=> [#81] ContentResponse DTO creatorName 응답값 추가

src/docs/asciidoc/api.adoc, src/main/java/com/hyperlink/server/domain/creator/application/CreatorService.java, src/main/java/com/hyperlink/server/domain/creator/controller/CreatorController.java, src/main/java/com/hyperlink/server/domain/creator/exception/CreatorNotFoundException.java, src/main/java/com/hyperlink/server/domain/memberCreator/domain/MemberCreatorRepository.java, src/main/java/com/hyperlink/server/domain/memberCreator/domain/entity/MemberCreator.java, src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java, src/test/java/com/hyperlink/server/creator/application/CreatorServiceIntegrationTest.java, src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java
- 비추천 크리에이터 추가 API 구현 및 테스트 작성
- 비추천 크리에이터 추가 API 구현 및 테스트 작성
- 테스트 코드 오류 수정
close #59
=> [#59] 비추천 크리에이터 추가 API 구현 및 테스트 작성

src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java
- test 코드 내부의 deleteAll() 메소드 변경
- 해당 PR 머지 후 원원원 내의 전체 크리에이터 목록 데이터 크롤링 후 dev DB insert 예정
- 유저 맞춤 크리에이터 추천 로직 테스트에서 활용할 예정
- DB insert는 프로젝트 내부 코드가 아닌 수기로 DB에 insert 할 계획이에요!
close #86
=> [#86] 크리에이터 더미 데이터 추가로 인한 테스트 코드 변경

build.gradle
- jacoco 커버리지 제외 클래스 경로 오류 수정
- 잘못 적용된 경로를 수정했어요!
close #95
=> [#95] jacoco 커버리지 제외 클래스 경로 오류 수정

src/main/java/com/hyperlink/server/domain/auth/token/AuthTokenExtractor.java, src/main/java/com/hyperlink/server/global/config/LoginMemberIdArgumentResolver.java, src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
- memberIdArgumentResolver 오류 수정 및 배포 확인에 필요한 uri 필터에서 제외
- memberIdArgumentResolver 오류 수정
- 배포 확인에 필요한 uri 필터에서 제외
close #100
=> [#100] memberIdArgumentResolver 오류 수정 및 배포 확인에 필요한 uri 필터에서 제외

src/test/java/com/hyperlink/server/memberContent/AuthSetupForMock.java
- 인증유저 단위테스트를 위한 setup 클래스 추가
- 인증유저 단위테스트를 위한 setup 클래스 추가
close #111
=> [#111] 인증유저 단위테스트를 위한 setup 클래스 추가

src/main/java/com/hyperlink/server/domain/auth/controller/AuthController.java, src/main/java/com/hyperlink/server/domain/auth/token/RefreshTokenCookieProvider.java
- cookie secure값 false로 변경
- cookie secure값 false로 변경
close #117
=> [#117] cookie secure값 false로 변경

src/main/java/com/hyperlink/server/domain/auth/controller/AuthController.java
- cd test 테스트용입니다.
- cd test 테스트용입니다.
close #119
=> [#119] cd 테스트용

src/test/java/com/hyperlink/server/content/controller/ContentRabbitMQIntegrationTest.java
- 컨텐츠 링크가 Dev DB에 있는 링크와 동일해서 생긴 문제입니다. 바로 해결해서 머지하겠습니다.
- 컨텐츠 링크 중복으로 인한 에러 코드 해결
close #124
=> [#124] HOTFIX RabbitMQ 통합 컨트롤러 테스트 수정

src/main/java/com/hyperlink/server/domain/auth/application/AuthService.java, src/main/java/com/hyperlink/server/domain/auth/controller/AuthController.java, src/main/java/com/hyperlink/server/domain/auth/dto/LoginRequest.java, src/main/java/com/hyperlink/server/domain/auth/oauth/GoogleAccessToken.java, src/main/java/com/hyperlink/server/domain/auth/oauth/GoogleOauthClient.java, src/main/java/com/hyperlink/server/domain/auth/oauth/dto/OauthResponse.java, src/main/java/com/hyperlink/server/domain/member/application/MemberService.java, src/main/java/com/hyperlink/server/domain/member/controller/MemberController.java, src/main/java/com/hyperlink/server/domain/member/dto/SignUpRequest.java, src/test/java/com/hyperlink/server/auth/application/AuthServiceTest.java, src/test/java/com/hyperlink/server/auth/controller/AuthControllerTest.java, src/test/java/com/hyperlink/server/global/exception/GlobalExceptionHandlerTest.java, src/test/java/com/hyperlink/server/member/application/MemberServiceIntegrationTest.java, src/test/java/com/hyperlink/server/member/controller/MemberControllerTest.java
-  멤버 로그인, 로그아웃, google oauth api 수정사항 변경
-  멤버 로그인 api 에서 요청 바디 값 제거
- 회원가입 api에서 RequestDTO부분 profileUrl 필드 제거 및 validation 수정
- google oauth api joincheck 부분 명시적으로 wasSignedUp으로 변경
close #122
=> [#122] 멤버 로그인, 회원가입, google oauth api 수정사항 변경

src/main/java/com/hyperlink/server/domain/content/controller/ContentController.java
- 검색 API 최신순으로 정렬 추가
- controller에 jwt 헤더 적용
- 검색 API에 최신순 정렬 기능을 추가했어요
- controller Test에 jwt는 멤버 쪽에서 알려주시면 추후 추가 예정입니다!
- 가능하시다면 시간되실 때 검색 API 구현 PR 코드 리뷰 부탁드립니다 🥹 (#46)
close #104
=> [#104] 검색 API 최신순으로 정렬 추가, jwt 헤더 적용

src/main/java/com/hyperlink/server/global/config/LoginMemberIdArgumentResolver.java
-  미인증 유저일 경우 고려하지않은 문제 해결
- 인증 유저일 경우 헤더값을 추출, 미인중  유저일 경우 바로 empty 값을 리턴하도록 변경
close #130
=> [#130] LoginArgumentResolver 문제 해결

src/main/java/com/hyperlink/server/global/config/WebConfig.java
- 프론트 배포 서버에 대한 cors 설정 변경
- 프론트 배포 서버에 대한 cors 설정 변경
close #138
=> [#138] 프론트 배포 서버에 대한 cors 설정 변경

src/main/java/com/hyperlink/server/global/config/WebConfig.java
- 프론트쪽 api 테스트를 위해 프론트 로컬호스트 cors에 추가
- 프론트쪽 api 테스트를 위해 프론트 로컬호스트 cors에 추가
프론트쪽의 요청으로 생성한 이슈이고, cors 추가 작업이기 때문에 approve없이 바로 머지합니다.
(김영빈님의 동의를 구했습니다.)
close #144
=> [#144] 프론트 로컬호스트 cors에 추가

src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
- cors preflight를 위한 Opitons 요청을 필터에서 제외
- cors preflight를 위한 Opitons 요청을 필터에서 제외
close #147
=> [#147] cors preflight를 위한 Opitons 요청을 필터에서 제외

src/docs/asciidoc/api.adoc, src/main/java/com/hyperlink/server/domain/content/application/ContentService.java, src/main/java/com/hyperlink/server/domain/content/controller/ContentController.java, src/main/java/com/hyperlink/server/domain/content/domain/entity/Content.java, src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java, src/test/java/com/hyperlink/server/content/controller/ContentControllerTest.java
- 어드민 페이지에서 컨텐츠를 활성화하는 기능을 구현했습니다.
- content 활성화 기능 구현
- content 활성화 테스트 코드 작성
- content 활성화 apidoc 작성
close #142
=> [#142] 어드민 페이지 컨텐츠 활성화 기능 구현

src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
- 조회수 갱신, 데일리브리핑 API whitelist 추가
- 비회원도 호출 가능한 API들 whitelist에 추가했어요
close #155
=> [#155] whitelist에 API url 추가

build.gradle, src/main/java/com/hyperlink/server/domain/member/controller/MemberController.java, src/main/java/com/hyperlink/server/domain/member/domain/entity/Member.java, src/main/java/com/hyperlink/server/domain/member/dto/ProfileImgResponse.java, src/main/java/com/hyperlink/server/domain/member/exception/ProfileImgUploadFailException.java, src/main/java/com/hyperlink/server/domain/member/s3/AwsS3Service.java, src/main/java/com/hyperlink/server/global/config/AwsS3Config.java, src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java, src/test/java/com/hyperlink/server/member/controller/MemberControllerMockTest.java
- 프로필 이미지 변경 api를 구현
- s3 연동
- multipartForm형식으로 request를 받아 s3에 업로드
yml 파일 변경 되어 노션 페이지에 적어놓겠습니다.
close #139
=> [#139] 프로필 이미지 변경 api 구현

src/main/java/com/hyperlink/server/domain/auth/application/AuthService.java, src/main/java/com/hyperlink/server/domain/auth/controller/AuthController.java, src/main/java/com/hyperlink/server/domain/auth/dto/LoginResponse.java, src/main/java/com/hyperlink/server/domain/auth/dto/LoginResult.java, src/main/java/com/hyperlink/server/domain/auth/dto/RenewResponse.java, src/main/java/com/hyperlink/server/domain/auth/dto/RenewResult.java, src/main/java/com/hyperlink/server/domain/auth/token/RefreshTokenCookieProvider.java, src/test/java/com/hyperlink/server/auth/application/AuthServiceTest.java, src/test/java/com/hyperlink/server/auth/controller/AuthControllerTest.java
- 로그인 및 토큰 재발급시 관리자인지 확인하는 필드 추가
- 로그인 및 토큰 재발급시 관리자인지 확인하는 필드 추가
- 추가로 로그아웃시 쿠키를 제거하는 로직 추가
close #152
=> [#152] 로그인 및 토큰 재발급시 관리자인지 확인하는 필드 추가

src/main/java/com/hyperlink/server/domain/company/domain/entity/Company.java, src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java, src/main/resources/db/migration/V19__add_column_is_using_recommend.sql, src/main/resources/db/migration/V20__change_column_isUsingRecommend.sql, src/test/java/com/hyperlink/server/attentionCategory/application/AttentionCategoryServiceIntegrationTest.java, src/test/java/com/hyperlink/server/member/application/MemberServiceIntegrationTest.java, src/test/java/com/hyperlink/server/member/controller/MemberControllerTest.java
- company table에 is_using_recommend 컬럼 추가
- company table에 is_using_recommend 컬럼 추가
close #158
=> [#158] company table에 is_using_recommend 컬럼 추가

src/main/java/com/hyperlink/server/domain/content/controller/ContentController.java
- 타팀원이 실수로 변경하여 잘못 적용된 메소드 맵핑 오류 수정
- 오류 발견하여 수정
close #161
=> [#161] 검색 API 메소드 맵핑 오류 수정

src/main/java/com/hyperlink/server/domain/content/infrastructure/ContentRepositoryCustom.java
- select entity 쿼리에서 count 쿼리로 수정
close #165
=> [#165] 검색 querydsl 메소드 size 쿼리 수정

src/main/java/com/hyperlink/server/domain/creator/application/CreatorService.java
- CreatorService transaction 오류 수정
- CreatorService 상단에 붙은 readOnly로 인해 insert 작업이 있는 메소드에 별도로 어노테이션 붙여줌
close #169
=> [#169] CreatorService transaction 오류 수정

build.gradle, src/docs/asciidoc/api.adoc, src/main/java/com/hyperlink/server/domain/company/application/CompanyService.java, src/main/java/com/hyperlink/server/domain/company/controller/CompanyController.java, src/main/java/com/hyperlink/server/domain/company/dto/MailRequest.java, src/main/java/com/hyperlink/server/domain/company/exception/MailAuthInvalidException.java, src/main/java/com/hyperlink/server/domain/company/mail/MailAuth.java, src/main/java/com/hyperlink/server/domain/company/mail/MailAuthRepository.java, src/main/java/com/hyperlink/server/domain/member/controller/MemberController.java, src/main/java/com/hyperlink/server/domain/member/domain/entity/Member.java, src/test/java/com/hyperlink/server/company/application/CompanyServiceIntegrationTest.java, src/test/java/com/hyperlink/server/company/controller/CompanyControllerTest.java, src/test/java/com/hyperlink/server/content/controller/ContentControllerTest.java
- 회사이메일 인증번호 요청 api
- Redis에 email과 인증번호를 저장(5분)
- JavaMailSender를 이용하여 해당 메일로 인증번호 전송
close #157
=> [#157] 회사이메일 인증번호 요청 api

src/test/java/com/hyperlink/server/content/controller/ContentRabbitMQIntegrationTest.java
- RabbitMQ 통합 테스트 독립적으로 수행되도록 변경
- 기존의 데이터가 있어야만 성공하던 테스트에서 독립된 환경에서도 성공할 수 있는 테스트 코드로 변경했습니다.
close #187
=> [#187] RabbitMQ 통합 테스트 코드 수정

src/main/java/com/hyperlink/server/domain/subscription/application/SubscriptionService.java
- 프론트엔드와 API 연동 중 구독 등록/취소 API에 문제가 있는 것을 파악하고 이를 고칩니다.
- SubscriptionService에 Transactional 선언
- HotFix이고 작업이 무겁지 않은 만큼 Approve 없이 머지하겠습니다. 양해부탁드립니다.
close #208
=> [#208] HOTFIX 구독 등록/취소 기능 수정

src/docs/asciidoc/api.adoc, src/main/java/com/hyperlink/server/domain/company/application/CompanyService.java, src/main/java/com/hyperlink/server/domain/company/controller/CompanyController.java, src/main/java/com/hyperlink/server/domain/company/domain/entity/Company.java, src/test/java/com/hyperlink/server/company/application/CompanyServiceIntegrationTest.java, src/test/java/com/hyperlink/server/company/controller/CompanyControllerTest.java
- 회사를 추천 서비스에 추가하는 api 개발
- 회사 테이블의 isUsingRecommend 필드를 기본값 false에서 true로 변경
close #212
=> [#212] 회사를 추천 서비스에 추가하는 api 개발

src/main/java/com/hyperlink/server/domain/company/controller/CompanyController.java, src/test/java/com/hyperlink/server/company/controller/CompanyControllerTest.java
- company 추천서비스 여부 변경 api uri 수정
- company 추천서비스 여부 변경 api uri 수정
close #223
=> [#223] company 추천서비스 여부 변경 api uri 수정

src/main/java/com/hyperlink/server/domain/company/application/CompanyService.java, src/test/java/com/hyperlink/server/company/application/CompanyServiceIntegrationTest.java
- 회사 조회 api page기준값 수정
- 회사 조회 api page기준값 수정
close #225
=> [#225] 회사 조회 api page기준값 수정

src/main/java/com/hyperlink/server/domain/dailyBriefing/DailyBriefingScheduler.java, src/main/java/com/hyperlink/server/domain/dailyBriefing/application/DailyBriefingService.java, src/main/java/com/hyperlink/server/global/config/RedisConfig.java
- redisTemplate Value Object로 변경 (RedisConfig.class)
- value값이 String일 수도 있기 때문에 GetDailyBriefingResponse에서 Object로 변경함
- redisTemplate과 연동된 코드 변경
close #238
=> [#238] redisTemplate Value Object로 변경

src/main/java/com/hyperlink/server/domain/auth/token/AuthTokenExtractor.java, src/main/java/com/hyperlink/server/domain/member/application/MemberService.java, src/main/java/com/hyperlink/server/global/config/WebConfig.java, src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java, src/main/java/com/hyperlink/server/global/filter/AuthorizationFilter.java, src/test/java/com/hyperlink/server/AuthSetupForMock.java, src/test/java/com/hyperlink/server/member/application/MemberServiceIntegrationTest.java
- 인가 필터 개발 및 필터 예외처리 수정
- 인가 필터 개발
- 필터 예외처리 body값 담아서 일관성 유지
- httpRequest.getHeader(HttpHeaders.AUTHORIZATION) 에서 발생하는 MalformedJwtException 처리
close #213
=> [#213] 인가 필터 개발 및 필터 예외처리 수정

src/main/java/com/hyperlink/server/domain/common/ContentDtoFactoryService.java
- Content dto에 Like여부 확인해서 전달
- ContentDtoFactoryService에서 memberContentRepository를 통해 Like여부 확인해서 전달
close #230
=> [#230] Content dto에 로그인 멤버의 Like여부 확인해서 전달하기

src/docs/asciidoc/api.adoc, src/main/java/com/hyperlink/server/domain/company/application/CompanyService.java, src/main/java/com/hyperlink/server/domain/company/controller/CompanyController.java, src/main/java/com/hyperlink/server/domain/company/domain/entity/Company.java, src/main/java/com/hyperlink/server/domain/company/dto/CompanyChangeNameRequest.java, src/test/java/com/hyperlink/server/company/application/CompanyServiceIntegrationTest.java, src/test/java/com/hyperlink/server/company/controller/CompanyControllerTest.java
- 회사 이름 변경 api 개발
- 어드민 페이지에서 사용할 회사 이름을 변경하는 api 개발
close #235
=> [#235] 회사 이름 변경 api 개발

src/main/java/com/hyperlink/server/domain/admin/controller/AdminController.java, src/main/java/com/hyperlink/server/domain/notRecommendCreator/domain/NotRecommendCreatorRepository.java, src/main/java/com/hyperlink/server/domain/subscription/domain/SubscriptionRepository.java, src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
- 배치 작업 수동실행 어드민 API 구현
- 서버 내부에서 테스트를 위해서 수동실행 API 구현
- sql param 오류 수정
- 머지 먼저 하겠습니다 양해부탁드려요🥲
close #247
=> [#247] 배치 작업 수동실행 어드민 API 구현

src/main/java/com/hyperlink/server/domain/admin/controller/AdminController.java, src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
- 배치 작업 수동 실행 API url 변경
- 현재 로그인 작업이 불가능하여 API 테스트가 불가능하기 때문에 부득이하게 필터 whitelist에 등록했어요
추후 삭제 예정이에요 /admin url이 blacklist에 추가되어 있어서 접근이 막혀있기 때문에 /test로 변경했어요
close #249
=> [#249] 배치 작업 수동 실행 API url 변경

src/main/java/com/hyperlink/server/global/filter/AuthorizationFilter.java
- 인가 필터에서 options 메소드 허용시키기
- Cors의 preflight를 통과시키기 위해 인가필터에서 options 메소드를 허용합니다.
close #254
=> [#254] 인가 필터에서 options 메소드 허용시키기

src/main/java/com/hyperlink/server/domain/dailyBriefing/domain/vo/MemberStatistics.java, src/main/java/com/hyperlink/server/domain/dailyBriefing/domain/vo/ViewStatistics.java
- 데일리브리핑 응답값 필드명 변경
- 프론트 요청사항에 따라서 필드명을 변경했어요
close #264
=> [#264] 데일리브리핑 응답값 필드명 변경

src/docs/asciidoc/api.adoc, src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java
- 추천 크리에이터 조회 API RestDocs 작성
close #266
=> [#266] 추천 크리에이터 조회 API RestDocs 작성

src/main/java/com/hyperlink/server/ServerApplication.java, src/main/java/com/hyperlink/server/global/config/BatchJobConfig.java
- EnableBatchProcessing 어노테이션 위치 변경
- main 클래스에서 batch config 파일로 EnableBatchProcessing 어노테이션 위치 변경
close #271
=> [#271] EnableBatchProcessing 어노테이션 위치 변경

src/main/java/com/hyperlink/server/domain/category/domain/CategoryRepository.java, src/test/java/com/hyperlink/server/category/domain/CategoryRepositoryTest.java, src/test/java/com/hyperlink/server/content/domain/ContentRepositoryTest.java, src/test/java/com/hyperlink/server/creator/domain/CreatorRepositoryTest.java
- Repository Test SpringBootTest에서 DataJpaTest로 변경
- spring batch 환경 분리하여 SpringbootTest에서 DataJpaTest로 변경
close #273
=> [#273] Repository Test SpringBootTest에서 DataJpaTest로 변경

src/main/java/com/hyperlink/server/domain/dailyBriefing/application/DailyBriefingService.java, src/main/java/com/hyperlink/server/domain/dailyBriefing/controller/DailyBriefingScheduler.java
- 데일리브리핑 데이터 redis expire 설정
- 데일리브리핑 데이터가 redis에서 2일 뒤에 자동 삭제되도록 expire 설정
close #284
=> [#284] 데일리브리핑 데이터 redis expire 설정

src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java, src/main/java/com/hyperlink/server/global/filter/AuthorizationFilter.java
- 필터 오류 응답 한글깨짐 해결
- 필터 오류 응답시 한글이 깨지는 문제를 해결하기 위해
response.Charset을 utf-8로 설정
close #278
=> [#278] 필터 오류 응답 한글깨짐 해결

src/test/java/com/hyperlink/server/attentionCategory/controller/AttentionCategoryControllerTest.java, src/test/java/com/hyperlink/server/auth/controller/AuthControllerMockTest.java, src/test/java/com/hyperlink/server/auth/controller/AuthControllerTest.java, src/test/java/com/hyperlink/server/member/controller/MemberControllerMockTest.java, src/test/java/com/hyperlink/server/member/controller/MemberControllerTest.java
- mockMvc테스트에  추가된 char-set=utf-8 추가
- mockMvc테스트에  추가된 char-set=utf-8 추가
close #286
=> [#286] mockMvc테스트에  추가된 char-set=utf-8 추가

src/test/java/com/hyperlink/server/auth/controller/AuthControllerMockTest.java
- mockMvc utf-8 타입 추가
- mockMvc utf-8 타입 추가
close #288
=> [#288]  mockMvc utf-8 타입 추가

src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java, src/main/java/com/hyperlink/server/global/filter/AuthorizationFilter.java
- Filter 메시지 한글깨짐 문제 해결
- Filter 메시지 한글깨짐 문제 해결
close #286
=> [#286] Filter 메시지 한글깨짐 문제 해결

src/main/java/com/hyperlink/server/domain/auth/controller/AuthControllerMockTest.java, src/test/java/com/hyperlink/server/attentionCategory/controller/AttentionCategoryControllerTest.java, src/test/java/com/hyperlink/server/auth/controller/AuthControllerMockTest.java, src/test/java/com/hyperlink/server/auth/controller/AuthControllerTest.java, src/test/java/com/hyperlink/server/member/controller/MemberControllerMockTest.java, src/test/java/com/hyperlink/server/member/controller/MemberControllerTest.java
- utf-8 테스트 코드 수정
- utf-8 테스트 코드 수정
close #292
=> utf-8 테스트 코드 수정

src/main/java/com/hyperlink/server/domain/auth/controller/AuthControllerMockTest.java, src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java, src/main/java/com/hyperlink/server/global/filter/AuthorizationFilter.java, src/test/java/com/hyperlink/server/attentionCategory/controller/AttentionCategoryControllerTest.java, src/test/java/com/hyperlink/server/auth/controller/AuthControllerMockTest.java, src/test/java/com/hyperlink/server/auth/controller/AuthControllerTest.java, src/test/java/com/hyperlink/server/member/controller/MemberControllerMockTest.java, src/test/java/com/hyperlink/server/member/controller/MemberControllerTest.java
- 필터 401 메시지 한글 깨짐 문제 해결
- 필터 401 메시지 한글 깨짐 문제 해결
=> 필터 401 메시지 한글 깨짐 문제 해결

src/main/java/com/hyperlink/server/domain/company/controller/CompanyController.java, src/main/java/com/hyperlink/server/domain/company/dto/MailAuthVerifyRequest.java
- 회사 인증 dto 유효성 변경
- 회사 이메일 인증 api dto 유효성 문제 해결
close #295
=> [#295] 회사 인증 dto 유효성 변경

src/main/java/com/hyperlink/server/domain/company/dto/MailAuthVerifyRequest.java
- 회사 인증 dto 변경
- 회사 인증 dto 변경
close #295
=> [#295] 회사 인증 dto 변경

src/main/java/com/hyperlink/server/global/config/WebConfig.java
- 프론트 임시 배포 도메인 origin 추가
- 프론트 임시 배포 도메인 origin 추가
close #298
=> [#298] 프론트 임시 배포 도메인 origin 추가

src/main/java/com/hyperlink/server/domain/content/infrastructure/ContentRepositoryCustom.java
- isViewable한 게시글만 볼 수 있도록 변경
close #201
=> [#201] isViewable 한 컨텐츠만 메인페이지에서 조회할 수 있도록 변경하기

src/main/java/com/hyperlink/server/domain/auth/application/AuthService.java, src/main/java/com/hyperlink/server/domain/auth/token/AuthTokenExtractor.java
- loginMemberArgumentResolver에서 토큰 존재하지만 유효하지않을경우 empty값 반환
- loginMemberArgumentResolver에서 토큰 존재하지만 유효하지않을경우 empty값 반환
close #302
=> [#302] loginMemberArgumentResolver에서 토큰 존재하지만 유효하지않을경우 empty값 반환

src/test/java/com/hyperlink/server/auth/token/AuthTokenExtractorTest.java
- extractMemberIdInCorrectTest empty값 반환으로 수정
- extractMemberIdInCorrectTest empty값 반환으로 수정
close #302
=> [#302] extractMemberIdInCorrectTest empty값 반환으로 수정

src/main/java/com/hyperlink/server/domain/memberHistory/application/MemberHistoryService.java, src/main/java/com/hyperlink/server/domain/memberHistory/controller/MemberHistoryController.java, src/main/java/com/hyperlink/server/domain/memberHistory/domain/MemberHistoryRepository.java
- 히스토리 전체 내역 조회 중복값 제거
- QA 중 오류 수정!!
close #262
=> [#262] 히스토리 전체 내역 조회 중복값 제거

src/main/java/com/hyperlink/server/domain/content/infrastructure/ContentRepositoryCustom.java, src/test/java/com/hyperlink/server/subscription/application/SubscriptionServiceIntegrationTest.java
- 구독 피드에 대해 isViewable 한 글만 볼 수 있도록 변경
- 그에 맞추어 테스트 코드 변경
#201
#300 
#303 
#305 
close #201
=> [#201] isViewable 한 글만 볼 수 있도록 변경

src/main/java/com/hyperlink/server/domain/company/application/CompanyService.java, src/main/java/com/hyperlink/server/domain/company/domain/entity/Company.java, src/main/java/com/hyperlink/server/domain/company/dto/MailAuthVerifyRequest.java, src/test/java/com/hyperlink/server/company/application/CompanyServiceIntegrationTest.java, src/test/java/com/hyperlink/server/company/controller/CompanyControllerTest.java, src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java, src/test/java/com/hyperlink/server/member/application/MemberServiceIntegrationTest.java, src/test/java/com/hyperlink/server/member/controller/MemberControllerTest.java
-  회사 이메일 인증 api dto 로고uri 필드 제거
-  회사 이메일 인증 api dto 로고uri 필드 제거
close #312
=> [#312] 회사 이메일 인증 api dto 로고uri 필드 제거

src/main/java/com/hyperlink/server/domain/subscription/application/SubscriptionService.java
- 아무도 구독하지 않았을 때 어떤 컨텐츠도 나오지 않도록 변경
close #314
=> [#314] 🚨HOTFIX🚨 구독하지 않았을 때 모든 글이 보이는 문제 해결

src/main/java/com/hyperlink/server/domain/company/application/CompanyService.java
- company Optional.orget() 수정
- company Optional.orget() 수정
close #318
=> [#318] company Optional.orget() 수정

src/main/java/com/hyperlink/server/domain/memberContent/application/BookmarkService.java
- 북마크 전체조회시 isLiked 항상 false인 문제 해결
- 북마크 전체조회시 isLiked 항상 false인 문제 해결
close #322
=> [#322] 북마크 전체조회시 isLiked 항상 false인 문제 해결

src/main/java/com/hyperlink/server/domain/creator/domain/CreatorRecommendService.java, src/main/resources/static/docs/api.html
- 크리에이터 추천풀이 아직 생성 안된 회원의 경우 랜덤으로 응답하기
- 새벽 4시에 한번 생성되는 크리에이터 추천풀이 아직 생성 안된 회원이 API를 요청했을 때 에러가 발생
- 랜덤으로 응답하도록 변경했어요!
close #325
=> [#325] 크리에이터 추천풀이 아직 생성 안된 회원의 경우 랜덤으로 응답하기

src/main/java/com/hyperlink/server/domain/creator/domain/CreatorRecommendService.java, src/main/java/com/hyperlink/server/domain/memberContent/application/BookmarkService.java, src/main/resources/static/docs/api.html
=> [#325] main으로 머지 🐥

src/main/java/com/hyperlink/server/domain/dailyBriefing/application/DailyBriefingService.java
- 데일리브리핑 redis key 값 오류 수정
- key 값이 잘못 적혀있어서 오류가 발생하여 수정했어요!
close #328
=> [#328] 데일리브리핑 redis key 값 오류 수정

src/main/java/com/hyperlink/server/domain/dailyBriefing/application/DailyBriefingService.java, src/main/java/com/hyperlink/server/domain/dailyBriefing/domain/vo/ContentStatistics.java
- 데일리브리핑 컨텐츠 증가분 조회 에러 수정
- LocalDateTime -> LocalDate로 수정
close #331
=> [#331] 데일리브리핑 컨텐츠 증가분 조회 에러 수정

src/main/java/com/hyperlink/server/domain/dailyBriefing/application/DailyBriefingService.java, src/main/java/com/hyperlink/server/domain/dailyBriefing/domain/vo/ContentStatistics.java
=> 🎣 데일리브리핑 일자별 컨텐츠 증가분 조회 에러 수정

src/main/java/com/hyperlink/server/domain/content/infrastructure/ContentRepositoryCustom.java, src/main/resources/static/docs/api.html
- 게시글이 중복되어 조회되는 현상 해결
close #334
=> [#334] HOTFIX 게시글이 중복되어 보이는 문제 발생

src/test/java/com/hyperlink/server/content/domain/ContentRepositoryTest.java
- 불필요한 코드 잘못 들어간 것 삭제
- 잘못된 코드가 들어갔어요🥲 에러 수정!!!
close #338
=> [#338] 불필요한 코드 잘못 들어간 것 삭제

README.md
=> 🦦 검색 정렬 기준 추가
