build.gradle
src/docs/asciidoc/api.adoc

- 적용 방법
1. Controller 테스트 작성
2. Controller 테스트 돌리기
3. /build/generated-snippets 경로로 들어가면 Controller 테스트에 해당하는 adoc 파일이 생성된 것을 확인할 수 있어요
4. /src/docs/asciidoc/api.adoc 파일 내에 API에 해당하는 명세 작성 (adoc 파일 추가)
api.adoc 파일에 예시로 테스트 api 명세를 추가해놓았어요
추후에 삭제할 예정이에요!
close #3

[#3] Rest Docs Asciidoc 설정

---

build.gradle

- jacoco report, coverage 설정
- 전체 test 실행 후 build/jacocoHtml 경로에 들어가시면 jacoco가 생성해준 report(html 파일)를 확인하실 수 있어요 (커버리지 수치, 내용)
- 80% 미달 시 빌드 실패하도록 설정했어요
- 현재는 작성한 테스트 코드가 전혀 없기 때문에 CI에서 빌드 실패가 발생될 것 같아요 (커버리지 80% 미달)
- 어느 정도 개발이 진행되기 전까지는 감수해야할 것 같아요!
- 이번주 내로 개발 진행하면서 80%까지 끌어올려야 할 것 같습니다
close #4

[#4] jacoco report, coverage 설정

---

.github/workflows/ci-prod.yml
src/docs/asciidoc/api.adoc

- 기존 Develop 환경에서와 비슷하게 Production 환경에 대한 블루/그린 무중단 배포를 구성했습니다.
- Production 환경에는 main 브랜치에 push, pr 시에만 CI/CD되며, CI의 경우 이미 develop 브랜치를 거쳐야 main 브랜치로 넘어가도록 하기 때문에 빌드 테스트는 진행하지 않습니다.(테스트 코드에서 더미 데이터를 실제 production DB에 저장하는 불상사를 막기 위한 목적도 있습니다.)
- 기존 develop 환경에 대한 CD는 그대로 유지했습니다.
- CI의 경우에만 다른 S3 버킷, 다른 Code Deploy 그룹, 등의 차이가 있어서 ci-prod.yml 파일을 만들었습니다.
- main 브랜치에 Push, PR될 경우에만 동작합니다.
- 내부적으로는 application-prod.yml이 아닌 application.yml로 사용하게 했으며 application-prod.yml은 깃허브의 secret key로 두어 사용했습니다.
- CI / CD 적용기 글을 작성할 예정입니다. 궁금하신 점이 있다면 해당 문서를 참고해주셔도 좋을 것 같습니다!
close #15

[#15] Production 환경에 대한 CI/CD 구축

---

build.gradle
src/main/java/com/hyperlink/server/global/exception/GlobalExceptionHandler.java

- jacoco 테스트 커버리지 측정 대상 클래스를 수정하고 사용하지 않는 GlobalExceptionHandler 메서드를 제거
- Method : handleUnexpectedException -> jacoco 커버리지 측정 제외는 실패함 -> 클래스, 패키지 단위로만 제외 가능
- Method : handleFileSizeLimitedMethod() -> 코드 내 삭제
- Class : ProfileController -> jacoco 커버리지 측정 제외
close #38

[#38] jacoco 테스트 빌드 대상 항목 수정

---

src/main/java/com/hyperlink/server/domain/content/domain/entity/Content.java
src/main/resources/db/migration/V4__add_column_inqu.sql
src/main/resources/db/migration/V5__datetime_auto.sql

- content table 조회수 컬럼 추가
- 모든 table created_at, updated_at 자동 업데이트 추가
- content table에 조회수 관련된 컬럼이 없어서 추가했어요
- created_at, updated_at 컬럼의 자동 업데이트 설정을 추가했어요
close #35

[#35] DB 컬럼 추가 및 컬럼 속성 추가

---

src/main/resources/crawling-scripts/develop/crawling-d2-develop.js
src/main/resources/crawling-scripts/develop/crawling-daangn-develop.js
src/main/resources/crawling-scripts/develop/crawling-kakao-develop.js
src/main/resources/crawling-scripts/develop/crawling-kurly-develop.js
src/main/resources/crawling-scripts/develop/crawling-toss-develop.js
src/main/resources/crawling-scripts/fashion/crawling-vogue-beauty.js
src/main/resources/crawling-scripts/fashion/crawling-vogue-fashion.js

- 개발, 패션 블로그 크롤링 기능 추가
- 개발 블로그 크롤링(2022.01 이후의 데이터 크롤링함)
- 대상 기업
- 네이버
- 카카오
- 당근마켓
- 마켓컬리
- 토스
- 패션 블로그 or 매거진 크롤링(데이터의 양이 많아 최신 120개의 데이터 크롤링함)
- 대상 매거진
- VOGUE 패션 매거진
- VOGUE 뷰티 매거진
- 현재 데이터를 DB에 저장하는 단계는 아니므로 DB에서 확인할 수 없는 점 유의바랍니다.
- 다음 이슈 PR에서 DB에 저장하도록 진행하겠습니다.
- js 스크립트 코드는 리뷰 목적으로만 존재하며 실제 서비스 단계에서는 동작하지 않는 것이 정상입니다. 다른 인스턴스에서 크롤링 작업을 진행할 것입니다.
close #28

[#28] 블로그 글 크롤링 기능 구현

---

src/main/java/com/hyperlink/server/domain/category/domain/CategoryRepository.java
src/main/java/com/hyperlink/server/domain/category/domain/entity/Category.java
src/main/java/com/hyperlink/server/domain/category/exception/CategoryNotFoundException.java
src/main/java/com/hyperlink/server/domain/creator/application/CreatorService.java
src/main/java/com/hyperlink/server/domain/creator/controller/CreatorController.java
src/main/java/com/hyperlink/server/domain/creator/domain/entity/Creator.java
src/main/java/com/hyperlink/server/domain/creator/dto/CreatorEnrollRequest.java
src/main/java/com/hyperlink/server/domain/creator/dto/CreatorEnrollResponse.java
src/test/java/com/hyperlink/server/category/domain/CategoryRepositoryTest.java
src/test/java/com/hyperlink/server/creator/application/CreatorServiceIntegrationTest.java
src/test/java/com/hyperlink/server/creator/application/CreatorServiceMockTest.java
src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java

- 크리에이터 생성 로직 구현
- 크리에이터 생성 로직 구현
- 크리에이터 생성 로직 테스트 코드 작성
- 커밋 메시지에도 적혀있지만, Admin 페이지에서만 크리에이터를 생성할 수 있도록 관리할 예정이에요.
- 이를 위해서, Member 도메인에서 해당 사용자가 관리자인지 아닌지 확인하는 로직이 필요할 것 같아요.
- 수요일 스크럼 시간에 이야기해보면 좋겠습니다.
@kivv00ng @yeeeze 
close #66

[#66] Creator 생성 로직 구현

---

build.gradle
src/main/java/com/hyperlink/server/domain/content/application/ContentService.java
src/main/java/com/hyperlink/server/domain/content/controller/ContentConsumer.java
src/main/java/com/hyperlink/server/domain/content/domain/ContentRepository.java
src/main/java/com/hyperlink/server/domain/content/dto/ContentCreationResponse.java
src/main/java/com/hyperlink/server/domain/content/dto/ContentEnrollResponse.java
src/main/java/com/hyperlink/server/domain/creator/domain/CreatorRepository.java
src/main/java/com/hyperlink/server/domain/creator/domain/entity/Creator.java
src/main/java/com/hyperlink/server/domain/memberCreator/domain/entity/MemberCreator.java~[#61] memberCreator table 생성
src/main/java/com/hyperlink/server/domain/memberCreator/domain/entity/MemberCreator.java~develop/v0.1
src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java
src/test/java/com/hyperlink/server/content/controller/ContentRabbitMQIntegrationTest.java
src/test/java/com/hyperlink/server/creator/domain/CreatorRepositoryTest.java

- 크롤링한 데이터를 메시지 큐를 통해 전달받아 DB에 저장합니다.
- 메시지큐로 RabbitMQ 사용
- DB에 MQ에 쌓인 데이터 저장
- prod 환경에서는 실제 DB에 저장되도록 세팅할 예정입니다.
- dev 환경에서는 실제 DB에 저장되지 않도록 테스트 코드에서만 사용합니다.
close #57

[#57] 크롤링 데이터 DB 업로드 기능 구현

---

src/main/java/com/hyperlink/server/domain/content/application/ContentService.java
src/main/java/com/hyperlink/server/domain/content/dto/GetContentsCommonResponse.java
src/main/java/com/hyperlink/server/domain/content/dto/SearchResponse.java
src/test/java/com/hyperlink/server/content/controller/ContentControllerTest.java

- content 도메인 공통 DTO 변경
- 공통 DTO로 GetContentsCommonResponse를 새로 생성했어요
- content domain API 개발 시 활용하시면 됩니다!
close #98

[#98] content 도메인 공통 DTO 변경

---

src/docs/asciidoc/api.adoc
src/main/java/com/hyperlink/server/domain/common/ContentDtoFactoryService.java
src/main/java/com/hyperlink/server/domain/content/application/ContentService.java
src/main/java/com/hyperlink/server/domain/content/dto/ContentResponse.java
src/main/java/com/hyperlink/server/domain/memberHistory/application/MemberHistoryService.java
src/main/java/com/hyperlink/server/domain/memberHistory/controller/MemberHistoryController.java
src/main/java/com/hyperlink/server/domain/memberHistory/domain/entity/MemberHistory.java
src/main/java/com/hyperlink/server/domain/memberHistory/domain/entity/MemberHistoryRepository.java
src/main/java/com/hyperlink/server/domain/notRecommendCreator/domain/entity/NotRecommendCreator.java
src/test/java/com/hyperlink/server/AuthSetupForMock.java
src/test/java/com/hyperlink/server/memberHistory/application/MemberHistoryIntegrationTest.java
src/test/java/com/hyperlink/server/memberHistory/controller/MemberHistoryControllerTest.java

- 히스토리 전체 내역 조회 API 구현 및 테스트 작성
- content domain 공통 응답 DTO 생성 로직 분리 (ContentDtoFactoryService)
- 유저의 전체 히스토리 내역을 조회하는 API를 개발했어요!
- content domain 공통 응답 DTO 생성 로직을 분리했어요!
- 기존에 memberContent 패키지 내부에 있던 AuthSetupForMock **공통 클래스**를 외부로 변경했어요 !
close #84

[#84] 히스토리 전체 내역 조회 API 구현 및 테스트

---

src/main/java/com/hyperlink/server/domain/content/application/ContentService.java
src/main/java/com/hyperlink/server/domain/content/controller/ContentController.java
src/main/java/com/hyperlink/server/domain/content/infrastructure/ContentRepositoryCustom.java
src/main/java/com/hyperlink/server/domain/creator/application/CreatorService.java
src/main/java/com/hyperlink/server/domain/creator/controller/CreatorController.java
src/main/java/com/hyperlink/server/domain/memberContent/controller/MemberContentController.java
src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java
src/test/java/com/hyperlink/server/content/controller/ContentControllerTest.java
src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java
src/test/java/com/hyperlink/server/memberContent/controller/MemberContentControllerTest.java

- 기존 개발 완료된 API에 jwt 헤더 추가
- 검색 API 최신순 정렬 오류 수정
- 기존 개발 완료된 API에 jwt 헤더 추가
- 검색 API 최신순 정렬 오류 수정
close #80

[#80] 기존 개발 완료된 API에 jwt 헤더 추가, 검색 API 오류 수정

---

src/docs/asciidoc/api.adoc
src/main/java/com/hyperlink/server/domain/creator/controller/CreatorController.java
src/main/java/com/hyperlink/server/domain/subscription/application/SubscriptionService.java
src/main/java/com/hyperlink/server/domain/subscription/controller/SubscriptionController.java
src/main/java/com/hyperlink/server/domain/subscription/domain/SubscriptionRepository.java
src/main/java/com/hyperlink/server/domain/subscription/domain/entity/Subscription.java
src/main/java/com/hyperlink/server/domain/subscription/dto/SubscribeResponse.java
src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java
src/test/java/com/hyperlink/server/subscription/application/SubscriptionServiceIntegrationTest.java
src/test/java/com/hyperlink/server/subscription/application/SubscriptionServiceMockTest.java
src/test/java/com/hyperlink/server/subscription/controller/SubscriptionControllerTest.java

- 크리에이터 구독 추가/삭제 기능 구현
- 크리에이터 구독 추가/삭제 기능 구현 및 테스트 코드를 작성했습니다.
- 코드 작업 중간에 AuthSetup 부분이 변경되어서 그에 맞게 다시 변경하여 테스트 코드 작성했습니다.
- JwtTokenProvider가 AuthSetUp 클래스 외부에 있었는데 내부로 이동한 것이 확인되어 그에 맞게 테스트 코드에서는 JwtTokenProvider를 제거해주었습니다.
- CreatorController에서 MockMvc를 사용한 Exception 발생 테스트 코드를 작성했습니다. 지난 #114 PR에서 다루었던 문제를 해결합니다.
close #137

[#137] 크리에이터 구독 추가/삭제 기능 구현

---

src/docs/asciidoc/api.adoc
src/main/java/com/hyperlink/server/domain/attentionCategory/domain/AttentionCategoryRepository.java
src/main/java/com/hyperlink/server/domain/category/domain/CategoryRepository.java
src/main/java/com/hyperlink/server/domain/common/ContentDtoFactoryService.java
src/main/java/com/hyperlink/server/domain/content/application/ContentService.java
src/main/java/com/hyperlink/server/domain/content/controller/ContentController.java
src/main/java/com/hyperlink/server/domain/content/domain/entity/Content.java
src/main/java/com/hyperlink/server/domain/content/dto/ContentResponse.java
src/main/java/com/hyperlink/server/domain/content/dto/RecommendationCompanyResponse.java
src/main/java/com/hyperlink/server/domain/content/exception/CategoryAndCreatorIdConstraintViolationException.java
src/main/java/com/hyperlink/server/domain/content/exception/InvalidSortException.java
src/main/java/com/hyperlink/server/domain/content/infrastructure/ContentRepositoryCustom.java
src/main/java/com/hyperlink/server/domain/memberContent/application/MemberContentService.java
src/main/java/com/hyperlink/server/global/exception/GlobalExceptionHandler.java
src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java
src/test/java/com/hyperlink/server/content/controller/ContentControllerTest.java
src/test/java/com/hyperlink/server/memberHistory/controller/MemberHistoryControllerTest.java

- 메인 페이지에 보일 컨텐츠 전체보기 기능을 구현했습니다.
- 카테고리 별로 최신, 인기 트렌드 보기
- 크리에이터 별로 최신, 인기 트렌드 보기
- 인기 트렌드의 경우 과거의 데이터를 가져오면 좋지 않을 것으로 판단하여 최근 5일 내의 데이터로 한정하여 조회하였습니다.
- 또한 정렬 기준은 조회수의 경우 1점, 좋아요수의 경우 3점으로 환산하여 합산 결과를 기반으로 정렬하였습니다.
- 작업한 내용은 기획상 로그인하지 않은 유저도 조회할 수 있으며 이 때 북마크 여부와 좋아요 여부는 모두 false 처리해야하기 때문에 예지님이 작업하셨던 isBookmarked 메서드를 조금 수정했습니다.
close #143

[#143] 메인 페이지에 보일 컨텐츠 전체보기 기능 구현

---

src/docs/asciidoc/api.adoc
src/main/java/com/hyperlink/server/domain/content/infrastructure/ContentRepositoryCustom.java
src/main/java/com/hyperlink/server/domain/subscription/application/SubscriptionService.java
src/main/java/com/hyperlink/server/domain/subscription/controller/SubscriptionController.java
src/main/java/com/hyperlink/server/domain/subscription/domain/SubscriptionRepository.java
src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java
src/test/java/com/hyperlink/server/content/controller/ContentControllerTest.java
src/test/java/com/hyperlink/server/subscription/application/SubscriptionServiceIntegrationTest.java
src/test/java/com/hyperlink/server/subscription/controller/SubscriptionControllerTest.java

- 구독 피드 탭에 들어갈 구독한 크리에이터가 작성한 글을 카테고리별, 전체카테고리로 조회하기 기능을 구현
- SubscriptionService에 조회 서비스 코드 로직 작성
- 그에 따른 ContentRepositoryCusom QueryDsl 코드 추가
- 컨트롤러, 서비스 통합 테스트 작성
- 전체 카테고리의 경우 infrastructure 계층인 repository 계층에서 도메인 로직(**0번일 때 전체 카테고리로 조회하기**)를 알고 있는 것이 좋지 않은 것으로 판단해, 따로 uri를 두어 /contents/all 같은 방식으로 만들었습니다.
close #160

[#160] 구독 피드 목록 조회 API 구현

---

src/docs/asciidoc/api.adoc
src/main/java/com/hyperlink/server/ServerApplication.java
src/main/java/com/hyperlink/server/domain/category/domain/CategoryRepository.java
src/main/java/com/hyperlink/server/domain/category/domain/vo/CategoryType.java
src/main/java/com/hyperlink/server/domain/content/controller/ContentConsumer.java
src/main/java/com/hyperlink/server/domain/content/controller/ContentController.java
src/main/java/com/hyperlink/server/domain/content/domain/ContentRepository.java
src/main/java/com/hyperlink/server/domain/dailyBriefing/DailyBriefingScheduler.java
src/main/java/com/hyperlink/server/domain/dailyBriefing/application/DailyBriefingService.java
src/main/java/com/hyperlink/server/domain/dailyBriefing/controller/DailyBriefingController.java
src/main/java/com/hyperlink/server/domain/dailyBriefing/domain/vo/CountStatisticsByCategory.java
src/main/java/com/hyperlink/server/domain/dailyBriefing/domain/vo/StatisticsType.java
src/main/java/com/hyperlink/server/domain/dailyBriefing/dto/DailyBriefing.java
src/main/java/com/hyperlink/server/domain/dailyBriefing/dto/GetDailyBriefingResponse.java
src/main/java/com/hyperlink/server/domain/dailyBriefing/dto/StatisticsByCategoryResponse.java
src/main/java/com/hyperlink/server/domain/dailyBriefing/infrastructure/DailyBriefingRepositoryCustom.java
src/main/java/com/hyperlink/server/domain/member/domain/MemberRepository.java
src/main/java/com/hyperlink/server/domain/memberHistory/domain/MemberHistoryRepository.java
src/main/java/com/hyperlink/server/global/config/RedisConfig.java
src/test/java/com/hyperlink/server/dailyBriefing/application/DailyBriefingServiceUnitTest.java
src/test/java/com/hyperlink/server/dailyBriefing/controller/DailyBriefingControllerTest.java
src/test/java/com/hyperlink/server/dailyBriefing/domain/vo/CountStatisticsByCategoryTest.java
src/test/java/com/hyperlink/server/dailyBriefing/infrastructure/DailyBriefingRepositoryCustomTest.java

- 데일리브리핑 API 구현 및 테스트 코드 작성
- 1시간 단위로 스케쥴러를 돌면서 데일리브리핑을 생성해요
- 스케쥴러에서 생성된 데일리브리핑 데이터를 redis에 저장하고 controller에서는 redis에 저장된 데이터를 읽는 로직이에요!
close #129

[#129] 데일리브리핑 API 구현 및 테스트 코드 작성

---

src/docs/asciidoc/api.adoc
src/main/java/com/hyperlink/server/domain/creator/application/CreatorService.java
src/main/java/com/hyperlink/server/domain/creator/controller/CreatorController.java
src/main/java/com/hyperlink/server/domain/creator/domain/CreatorRepository.java
src/main/java/com/hyperlink/server/domain/creator/dto/CreatorAndSubscriptionCountMapper.java
src/main/java/com/hyperlink/server/domain/creator/dto/CreatorResponse.java
src/main/java/com/hyperlink/server/domain/creator/dto/CreatorsRetrievalResponse.java
src/main/java/com/hyperlink/server/domain/creator/dto/SubscribeFlagMapper.java
src/main/java/com/hyperlink/server/domain/subscription/domain/SubscriptionRepository.java
src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
src/test/java/com/hyperlink/server/creator/application/CreatorServiceIntegrationTest.java
src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java
src/test/java/com/hyperlink/server/creator/domain/CreatorRepositoryTest.java

- 구독 정보, 구독자 수를 고려한 크리에이터 정보 조회 기능 구현
- Creator 레포지토리, 서비스 통합 테스트, 컨트롤러 슬라이스 테스트 구현
- 크리에이터 조회 api docs 추가
- 로그인, 비로그인 상태를 고려한 구독 상태 조회, 카테고리 별 크리에이터 조회 기능을 구현했습니다.
- 비로그인 상태에서도 조회가능해야 하므로 whitelist에 /creators 를 추가했습니다.
close #164

[#164] 카테고리별 크리에이터 목록 조회

---

src/docs/asciidoc/api.adoc
src/main/java/com/hyperlink/server/domain/attentionCategory/application/AttentionCategoryService.java
src/main/java/com/hyperlink/server/domain/attentionCategory/controller/AttentionCategoryController.java
src/main/java/com/hyperlink/server/domain/attentionCategory/domain/AttentionCategoryRepository.java
src/main/java/com/hyperlink/server/domain/member/application/MemberService.java
src/main/java/com/hyperlink/server/domain/member/controller/MemberController.java
src/test/java/com/hyperlink/server/attentionCategory/application/AttentionCategoryServiceIntegrationTest.java
src/test/java/com/hyperlink/server/attentionCategory/controller/AttentionCategoryControllerTest.java
src/test/java/com/hyperlink/server/member/application/MemberServiceIntegrationTest.java
src/test/java/com/hyperlink/server/member/controller/MemberControllerMockTest.java

- attentionCategory 변경시 이전 관심목록이 남아있던 문제 해결
- attentionCategory 변경시 이전 관심목록이 남아있던 문제 해결
- attentionCategory를 members에서 분리
close #190

[#190]: attentionCategory 변경시 이전 관심목록이 남아있던 문제 해결

---

src/docs/asciidoc/api.adoc
src/main/java/com/hyperlink/server/domain/creator/application/CreatorService.java
src/main/java/com/hyperlink/server/domain/creator/controller/CreatorController.java
src/main/java/com/hyperlink/server/domain/creator/domain/CreatorRepository.java
src/main/java/com/hyperlink/server/domain/creator/dto/CreatorAdminResponse.java
src/main/java/com/hyperlink/server/domain/creator/dto/CreatorAdminResponses.java
src/test/java/com/hyperlink/server/creator/application/CreatorServiceIntegrationTest.java
src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java

- Admin 페이지에서 크리에이터 관리를 위한 크리에이터 전체 조회 기능을 구현했습니다.
- 크리에이터 정보 가져올 때 카테고리 정보도 가져올 수 있도록 fetch join 사용해 N + 1 문제 해결
- 전체 조회 시 Slice 방법에서 Page 방법으로 변경했습니다.
- 바쁘신 분들은 0cdabd3d9c27ffbb66192f3b4c9e9f05103daf6f 만 보셔도 좋습니다.(Pagination 으로 변경함)
- PR 올린 후 rebase를 하면서 [0acacab](https://github.com/prgrms-web-devcourse/Team-JJINSA-HyperLink-BE/pull/200/commits/0acacab380bbd57e6f3658019ba4e0cb393d4297) 부터의 커밋이 생겼습니다. 이 부분은 무시하셔도 됩니다.
close #183

[#183] [어드민 페이지] 크리에이터 전체 조회 기능 구현

---

src/main/java/com/hyperlink/server/domain/creator/application/CreatorService.java
src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java

- 어드민 페이지 크리에이터 전체조회 페이지네이션의 currentPage 시작값을 0에서 1로 변경
- 어드민 페이지 크리에이터 전체조회 페이지네이션의 currentPage 시작값을 0에서 1로 변경
- 그에 따른, ControllerTest 코드 변경
close #217

[#217] 어드민 페이지 크리에이터 전체조회 페이지네이션의 현재 페이지값 변경

---

src/main/java/com/hyperlink/server/domain/creator/domain/CreatorRepository.java

- creator 조회 시 누락되는 문제 해결
- order by id로 정렬하여 해결
- 정렬 순서가 잘못되어서 구독여부, 구독자 수 간의 불일치가 생겨 조회되지 않는 문제였습니다.
- 정렬 순서를 맞춰서 해결했습니다.
close #227

[#227] 크리에이터 전체 조회 에러 수정

---

src/docs/asciidoc/api.adoc
src/main/java/com/hyperlink/server/domain/admin/application/AdminService.java
src/main/java/com/hyperlink/server/domain/admin/controller/AdminController.java
src/main/java/com/hyperlink/server/domain/admin/controller/AdminScheduler.java
src/main/java/com/hyperlink/server/domain/admin/domain/vo/CategoryAndView.java
src/main/java/com/hyperlink/server/domain/admin/dto/CategoryViewResponse.java
src/main/java/com/hyperlink/server/domain/admin/dto/CategoryViewResponses.java
src/main/java/com/hyperlink/server/domain/admin/dto/CountingViewByCategoryDto.java
src/main/java/com/hyperlink/server/domain/admin/exception/CategoryViewNotFoundException.java
src/main/java/com/hyperlink/server/domain/category/domain/CategoryRepository.java
src/main/java/com/hyperlink/server/domain/dailyBriefing/DailyBriefingScheduler.java
src/main/java/com/hyperlink/server/domain/dailyBriefing/application/DailyBriefingService.java
src/main/java/com/hyperlink/server/global/config/RedisConfig.java
src/test/java/com/hyperlink/server/admin/application/AdminServiceUnitTest.java
src/test/java/com/hyperlink/server/admin/controller/AdminControllerTest.java
src/test/java/com/hyperlink/server/category/domain/CategoryRepositoryTest.java

- 조회일 기준 7일전부터 7일동안의 카테고리별 조회수 통계를 제공합니다.
- Daily-Briefing과 동일하게 Redis를 사용하여 캐싱하였습니다.
- CategoryView 조회 기능 구현(어드민)
- CategoryView 테스트 코드 작성
close #210

[#210] 카테고리 별 하루의 조회수 증가분 계산하기 구현

---

src/main/java/com/hyperlink/server/domain/auth/application/AuthService.java
src/main/java/com/hyperlink/server/domain/auth/controller/AuthController.java
src/main/java/com/hyperlink/server/domain/auth/controller/AuthControllerMockTest.java
src/main/java/com/hyperlink/server/domain/auth/oauth/GoogleOauthClient.java
src/main/java/com/hyperlink/server/domain/member/controller/MemberController.java
src/test/java/com/hyperlink/server/auth/controller/AuthControllerMockTest.java
src/test/java/com/hyperlink/server/auth/controller/AuthControllerTest.java
src/test/java/com/hyperlink/server/member/controller/MemberControllerMockTest.java
src/test/java/com/hyperlink/server/member/controller/MemberControllerTest.java

- auth api 로그인 및 회원가입시 googleAccessToken 만료시키기
- auth api 로그인 및 회원가입시 googleAccessToken 만료시키기
close #220

[#220] auth api 로그인 및 회원가입시 googleAccessToken 만료시키기

---

src/main/java/com/hyperlink/server/domain/content/application/ContentService.java
src/main/java/com/hyperlink/server/domain/content/infrastructure/ContentRepositoryCustom.java

- 검색 API 전체 사이즈 에러 수정
- 검색 API 응답값 중에 전체 검색 결과 사이즈가 request size로 잘못 응답되는 오류가 있어서 수정했어요!
- Slice interface에는 totalElements 필드가 없어서 Page interface로 변경했어요
- hotfix인 관계로 머지 먼저 할게요! 😵
close #251

[#251] 검색 API 전체 사이즈 에러 수정

---

src/main/java/com/hyperlink/server/domain/admin/controller/AdminScheduler.java
src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java
src/test/java/com/hyperlink/server/admin/controller/AdminControllerTest.java
src/test/java/com/hyperlink/server/category/domain/CategoryRepositoryTest.java
src/test/java/com/hyperlink/server/content/application/ContentServiceIntegrationTest.java
src/test/java/com/hyperlink/server/content/domain/ContentRepositoryTest.java
src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java
src/test/java/com/hyperlink/server/creator/domain/CreatorRepositoryTest.java
src/test/java/com/hyperlink/server/dailyBriefing/controller/DailyBriefingControllerTest.java

- 테스트 코드가 동작하지 않던 문제를 해결했습니다.
- Spring Batch가 들어오면서 DataJpaTest가 붙은 테스트들은 전부 실패함.
- 이유는, Spring Batch가 트랜잭션을 사용할 때 DataJpaTest의 트랜잭션을 무시하게 만들어서 save 명령이 나가지 않는 문제 발생
- DataJpaTest 어노테이션을 SpringBootTest 어노테이션으로 변경하여 해결
- DailyBriefingControllerTest에서 Service 모킹 시 실제 컨트롤러에서 사용하는 getDailyBriefing 메서드를 모킹하지 않고 createDailyBriefing 메서드를 모킹중이어서 에러 발생했음
- 이를 해결함
close #256

[#256] 테스트 코드 오류 해결

---

src/main/java/com/hyperlink/server/domain/creator/controller/CreatorController.java
src/main/java/com/hyperlink/server/domain/creator/domain/CreatorRecommendService.java
src/main/java/com/hyperlink/server/global/filter/AuthenticationFilter.java

- 추천 크리에이터 조회 API 비회원 요청 금지
- 추천 크리에이터 조회 API 비회원은 요청하지 못하도록 금지했어요!
close #268

[#268] 추천 크리에이터 조회 API 비회원 요청 금지

---

src/main/java/com/hyperlink/server/domain/creator/domain/CreatorRecommendService.java

- 추천 크리에이터 조회 API 응답 중복값 제거
- 랜덤으로 추출되던 id 값이 중복되던 오류가 있어서 수정했어요
QA!!!!!!!! 😵
close #309

[#309] 추천 크리에이터 조회 API 응답 중복값 제거

---

src/main/java/com/hyperlink/server/domain/creator/dto/CreatorAdminResponse.java
src/test/java/com/hyperlink/server/creator/controller/CreatorControllerTest.java

- 어드민 페이지 크리에이터 전체 조회 필드 추가
- 컨트롤러 테스트 코드 변경
close #319

[#319] [Admin] 크리에이터 조회 페이지 프로필 이미지 링크 전송하도록 변경

---

src/main/java/com/hyperlink/server/domain/content/infrastructure/ContentRepositoryCustom.java
src/test/java/com/hyperlink/server/content/domain/ContentRepositoryTest.java

- 검색 응답 페이지 정렬 기준 변경
- 기존에 최신순 내림차순으로만 정렬하던 기준을 최신순, 히스토리 유저 클릭 패턴 분석 + 조회수로 변경했어요!
close #262

[#262] 검색 응답 페이지 정렬 기준 변경
